# Generated by Django 2.2.5 on 2022-04-24 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(db_index=True, upload_to='uploadedimages/', verbose_name='Путь до изображения')),
            ],
        ),
        migrations.CreateModel(
            name='BoxWithoutMask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(verbose_name='Х левый верхний')),
                ('y', models.IntegerField(verbose_name='Y левый верхний')),
                ('width', models.IntegerField(verbose_name='Ширина')),
                ('height', models.IntegerField(verbose_name='Высота')),
                ('source_image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.Images')),
            ],
        ),
    ]
